// src/blocks/SettingCard/SettingCard.tsx
import React from 'react'
import { classNames } from 'webcoreui'
import { Card, ConditionalWrapper } from 'webcoreui/react'

import type { SettingCardProps } from './settingCard'
import styles from './setting-card.module.scss'

export type Props = SettingCardProps & {
    children: React.ReactNode
    additionalContent?: React.ReactNode
}

const SettingCard = ({
    icon,
    title,
    subTitle,
    children,
    additionalContent,
    ...rest
}: Props) => {

    return (
        <Card
            secondary={true}
            flat={true}
            bodyClassName="flex column sm"
            {...rest}
        >
            <div className={classNames([
                styles.body,
                'flex justify-between items-center xs'
            ])}>
                <ConditionalWrapper
                    condition={!!icon}
                    wrapper={children => <div className="flex center">{children}</div>}
                >
                    {icon && (
                        <span
                            dangerouslySetInnerHTML={{ __html: icon }}
                            style={{ height: '21px' }}
                        />
                    )}

                    <div className="flex column xxs">
                        <div>{title}</div>
                        {subTitle && <div className="muted">{subTitle}</div>}
                    </div>
                </ConditionalWrapper>

                {children}
            </div>
            {additionalContent}
        </Card>
    )
}

export default SettingCard

// src/blocks/SettingCard/SettingCard.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import { classNames } from 'webcoreui'
    import { Card, ConditionalWrapper } from 'webcoreui/svelte'

    import type { SettingCardProps } from './settingCard'
    import styles from './setting-card.module.scss'

    export type Props = SettingCardProps & {
        children: Snippet
        additionalContent?: Snippet
    }

    const {
        icon,
        title,
        subTitle,
        children,
        additionalContent,
        ...rest
    }: Props = $props()
</script>

<Card
    secondary={true}
    flat={true}
    bodyClassName="flex column sm"
    {...rest}
>
    <div class={classNames([
        styles.body,
        'flex justify-between items-center xs'
    ])}>
        <ConditionalWrapper condition={!!icon} class="flex center">
            {#if icon}
                {@html icon}
            {/if}

            <div class="flex column xxs">
                <div>{title}</div>
                {#if subTitle}
                    <div class="muted">{subTitle}</div>
                {/if}
            </div>
        </ConditionalWrapper>

        {@render children?.()}
    </div>
    {@render additionalContent?.()}
</Card>
